version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - finance-network
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - finance-network
  keycloak:
    image: jboss/keycloak
    container_name: finance-keycloak
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=finance
      - DB_ADDR=finance-postgres
    depends_on:
      - postgres
    networks:
      - finance-network


networks:
  finance-network:
    